package emit

import (
	"io/fs"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestDockerIgnore(t *testing.T) {
	f := DockerIgnore([]string{"node_modules", ".git", "node_modules", "*.log", "", "  ", "# comment"})

	require.Equal(t, ".dockerignore", f.Path)
	require.Equal(t, fs.FileMode(0o644), f.Mode)
	require.Equal(t, strings.Join([]string{
		"# Generated by dockerizethis. Do not edit manually.",
		"*.log",
		".git",
		"node_modules",
		"",
	}, "\n"), string(f.Content))
}

func TestDockerIgnoreEmpty(t *testing.T) {
	f := DockerIgnore(nil)
	require.Equal(t, "# Generated by dockerizethis. Do not edit manually.\n", string(f.Content))
}
