package emit

import (
	"sort"
	"strings"
)

const dockerIgnorePath = ".dockerignore"

// DockerIgnore renders a .dockerignore from lines with duplicates removed and
// the rest sorted when no negations exist. Negated rules preserve input order
// and duplicates because the last matching rule wins. Blank/comments are dropped.
func DockerIgnore(lines []string) File {
	ordered := false
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "!") {
			ordered = true
		}
	}
	seen := make(map[string]struct{}, len(lines))
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if _, ok := seen[line]; ok && !ordered {
			continue
		}
		seen[line] = struct{}{}
		kept = append(kept, line)
	}
	if !ordered {
		sort.Strings(kept)
	}

	var b strings.Builder
	b.WriteString("# Generated by dockerize. Do not edit manually.\n")
	for _, line := range kept {
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return File{Path: dockerIgnorePath, Content: []byte(b.String()), Mode: defaultFileMode}
}
