package common_test

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/carl/dockerizethis/internal/emit"
	"github.com/carl/dockerizethis/internal/plan"
	"github.com/carl/dockerizethis/internal/templates/common"
	"github.com/stretchr/testify/require"
)

var update = flag.Bool("update", false, "update common template golden files")

func webPlan() plan.Plan {
	return plan.Plan{
		Stack: "node", Version: "22", PkgManager: "npm", Process: plan.ProcessWeb,
		Port: 3000, HealthPath: "/health", StartCmd: "node dist/server.js", Workdir: ".",
		Services: []plan.Service{plan.ServicePostgres, plan.ServiceRedis},
		Env: []plan.EnvVar{
			{Name: "DATABASE_URL", Required: true, Hint: "postgres connection string"},
			{Name: "REDIS_URL", Hint: "redis connection string"},
		},
	}
}

func TestRenderCommonGolden(t *testing.T) {
	for _, tc := range []struct {
		name   string
		change func(*plan.Plan)
	}{
		{"web-postgres-redis", func(p *plan.Plan) {}},
		{"worker-mongo", func(p *plan.Plan) {
			p.Process, p.Port, p.HealthPath = plan.ProcessWorker, 0, ""
			p.StartCmd = "node worker.js"
			p.Services = []plan.Service{plan.ServiceMongo}
			p.Env = []plan.EnvVar{{Name: "MONGO_URL", Required: true}}
		}},
		{"web-only", func(p *plan.Plan) {
			p.Services, p.Env = nil, nil
		}},
		{"web-optional-env", func(p *plan.Plan) {
			p.Services = nil
			p.Env = []plan.EnvVar{{Name: "PORT"}}
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := webPlan()
			tc.change(&p)
			renderers := []struct {
				kind   string
				render func(plan.Plan) (emit.File, error)
			}{
				{"compose", common.RenderCompose},
				{"action", common.RenderAction},
				{"deploy", common.RenderDeployDoc},
			}
			for _, r := range renderers {
				file, err := r.render(p)
				require.NoError(t, err)
				require.EqualValues(t, 0o644, file.Mode)
				output := fmt.Sprintf("--- %s (mode %04o) ---\n%s", file.Path, file.Mode, file.Content)
				golden := filepath.Join("..", "..", "..", "testdata", "golden", r.kind+"-"+tc.name+".golden")
				if *update {
					require.NoError(t, os.MkdirAll(filepath.Dir(golden), 0o755))
					require.NoError(t, os.WriteFile(golden, []byte(output), 0o644))
				}
				want, err := os.ReadFile(golden)
				require.NoError(t, err)
				require.Equal(t, want, []byte(output), "refresh with go test ./internal/templates/common -update")
			}
		})
	}
}

func TestComposeAppService(t *testing.T) {
	file, err := common.RenderCompose(webPlan())
	require.NoError(t, err)
	compose := string(file.Content)
	require.Equal(t, "docker-compose.yml", file.Path)
	require.Contains(t, compose, "# generated by dockerize — edit freely\n")
	require.Contains(t, compose, "    build: .\n    restart: unless-stopped\n")
	require.Contains(t, compose, "    env_file:\n      - .env\n")
	require.Contains(t, compose, `      - "3000:3000"`+"\n")
	for _, svc := range []string{"postgres", "redis"} {
		require.Contains(t, compose, "      "+svc+":\n        condition: service_healthy\n")
	}
	require.Contains(t, compose, "volumes:\n  postgres_data:\n")
	require.Contains(t, compose, "networks:\n  default:\n    driver: bridge\n")
}

func TestComposeConditionals(t *testing.T) {
	worker := webPlan()
	worker.Process, worker.Port = plan.ProcessWorker, 0
	worker.Services = []plan.Service{plan.ServiceMongo}
	worker.Env = nil
	file, err := common.RenderCompose(worker)
	require.NoError(t, err)
	compose := string(file.Content)
	require.NotContains(t, compose, "env_file")
	require.NotContains(t, compose, "ports:")
	require.Contains(t, compose, "      mongo:\n        condition: service_healthy\n")
	require.Contains(t, compose, "  mongo_data:\n")
	require.NotContains(t, compose, "postgres_data")

	bare := webPlan()
	bare.Services, bare.Env = nil, nil
	file, err = common.RenderCompose(bare)
	require.NoError(t, err)
	compose = string(file.Content)
	require.NotContains(t, compose, "depends_on")
	require.NotContains(t, compose, "\nvolumes:")
}

func TestComposeOptionalEnvironment(t *testing.T) {
	p := webPlan()
	p.Services = nil
	p.Env = []plan.EnvVar{{Name: "PORT"}}
	file, err := common.RenderCompose(p)
	require.NoError(t, err)
	require.Contains(t, string(file.Content), "    env_file:\n      - path: .env\n        required: false\n")

	p.Env = append(p.Env, plan.EnvVar{Name: "API_TOKEN", Required: true})
	file, err = common.RenderCompose(p)
	require.NoError(t, err)
	require.Contains(t, string(file.Content), "    env_file:\n      - .env\n")
	require.NotContains(t, string(file.Content), "required: false")
}

func TestComposeNeverEmitsEnvFile(t *testing.T) {
	for _, p := range []plan.Plan{webPlan(), {Env: nil}, {Env: []plan.EnvVar{{Name: "SECRET_KEY", Required: true}}}} {
		file, err := common.RenderCompose(p)
		require.NoError(t, err)
		require.Equal(t, "docker-compose.yml", file.Path,
			"compose renders exactly one file and it is never .env")
		require.NotContains(t, string(file.Content), "SECRET_KEY=")
	}
}

func TestComposeServiceBlocks(t *testing.T) {
	p := webPlan()
	p.Services = []plan.Service{plan.ServicePostgres, plan.ServiceRedis, plan.ServiceMySQL, plan.ServiceMongo}
	file, err := common.RenderCompose(p)
	require.NoError(t, err)
	compose := string(file.Content)
	for _, image := range []string{"postgres:16-alpine", "redis:7-alpine", "mysql:8", "mongo:7"} {
		require.Contains(t, compose, "image: "+image+"\n")
	}
	for _, probe := range []string{"pg_isready", "redis-cli", "mysqladmin", "mongosh"} {
		require.Contains(t, compose, probe)
	}
	for _, volume := range []string{"postgres_data", "mysql_data", "mongo_data"} {
		require.Contains(t, compose, "  "+volume+":\n")
	}
}

func TestComposeUnknownValues(t *testing.T) {
	p := webPlan()
	p.Process, p.Services = "cron", []plan.Service{"kafka", plan.ServiceRedis}
	file, err := common.RenderCompose(p)
	require.NoError(t, err)
	compose := string(file.Content)
	require.Contains(t, compose, `TODO: process type "cron"`)
	require.Contains(t, compose, `no compose block for service "kafka"`)
	require.NotContains(t, compose, "      kafka:")
	require.Contains(t, compose, "      redis:\n        condition: service_healthy\n")
}

func TestComposeInvalidPort(t *testing.T) {
	for _, process := range []plan.ProcessType{plan.ProcessWeb, plan.ProcessStatic} {
		for _, port := range []int{0, -1, 65536} {
			p := webPlan()
			p.Process, p.Port = process, port
			file, err := common.RenderCompose(p)
			require.ErrorContains(t, err, "port")
			require.Equal(t, emit.File{}, file)
		}
	}
	p := webPlan()
	p.Process, p.Port = plan.ProcessWorker, 0
	_, err := common.RenderCompose(p)
	require.NoError(t, err, "workers publish no port, so an unset port is valid")
}

func TestComposeStaticPublishesPort(t *testing.T) {
	p := webPlan()
	p.Process, p.Port = plan.ProcessStatic, 8080
	file, err := common.RenderCompose(p)
	require.NoError(t, err)
	require.Contains(t, string(file.Content), `      - "8080:8080"`+"\n",
		"static sites run nginx in the container and need a published port")
}

func TestRenderAction(t *testing.T) {
	file, err := common.RenderAction(webPlan())
	require.NoError(t, err)
	require.Equal(t, ".github/workflows/docker.yml", file.Path)
	action := string(file.Content)
	for _, want := range []string{
		"docker/setup-buildx-action@v3",
		"docker/build-push-action@v6",
		"REGISTRY: ghcr.io",
		"IMAGE_NAME: ${{ github.repository }}",
		`echo "IMAGE_NAME=${IMAGE_NAME,,}"`,
		"${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}",
		"${{ secrets.GITHUB_TOKEN }}",
		"packages: write",
		`tags: ["v*.*.*"]`,
		"branches: [main]",
	} {
		require.Contains(t, action, want)
	}
}

func TestRenderDeployDoc(t *testing.T) {
	file, err := common.RenderDeployDoc(webPlan())
	require.NoError(t, err)
	require.Equal(t, "DEPLOY.md", file.Path)
	doc := string(file.Content)
	for _, want := range []string{
		"docker compose up -d --build",
		"cp -n .env.example .env",
		"Caddy",
		"reverse_proxy localhost:3000",
		"postgres_data",
		"pg_dump",
	} {
		require.Contains(t, doc, want)
	}

	worker := webPlan()
	worker.Process, worker.Services = plan.ProcessWorker, []plan.Service{plan.ServiceMongo}
	file, err = common.RenderDeployDoc(worker)
	require.NoError(t, err)
	doc = string(file.Content)
	require.Contains(t, doc, "unless-stopped")
	require.Contains(t, doc, "mongo_data")
	require.Contains(t, doc, "mongodump")

	unknown := webPlan()
	unknown.Process, unknown.Services = "cron", []plan.Service{"kafka"}
	file, err = common.RenderDeployDoc(unknown)
	require.NoError(t, err)
	doc = string(file.Content)
	require.Contains(t, doc, `TODO: process type "cron"`)
	require.Contains(t, doc, "kafka")
	require.Contains(t, doc, "TODO")
}

func TestRenderersDoNotMutatePlan(t *testing.T) {
	p := webPlan()
	before := fmt.Sprintf("%v", p)
	for _, render := range []func(plan.Plan) (emit.File, error){
		common.RenderCompose, common.RenderAction, common.RenderDeployDoc,
	} {
		_, err := render(p)
		require.NoError(t, err)
	}
	require.Equal(t, before, fmt.Sprintf("%v", p))
}
